#!/usr/bin/env bash
# Ce script modifie le fichier /etc/hosts pour changer l'IP associée à localhost et facebook.com

# Sauvegarde du fichier /etc/hosts
sudo cp /etc/hosts /etc/hosts.bak

# Modification du fichier /etc/hosts
sudo sed -i '/127.0.0.1\s\+localhost/d' /etc/hosts
echo "127.0.0.2 localhost" | sudo tee -a /etc/hosts
echo "8.8.8.8 facebook.com" | sudo tee -a /etc/hosts

echo "Changements appliqués :"
echo "localhost => 127.0.0.2"
echo "facebook.com => 8.8.8.8"